# Generated by Django 4.2.1 on 2023-05-13 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=60)),
                ('bio', models.TextField(blank=True)),
                ('date_birth', models.DateField(null=True)),
                ('date_death', models.DateField(null=True)),
                ('picture', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=60)),
                ('release_date', models.DateField(null=True)),
                ('game_category', models.CharField(max_length=60)),
                ('game_info', models.TextField(blank=True)),
                ('game_developers', models.CharField(max_length=60)),
                ('game_publishers', models.CharField(max_length=60)),
            ],
        ),
        migrations.DeleteModel(
            name='Developer',
        ),
        migrations.AddField(
            model_name='company',
            name='games',
            field=models.ManyToManyField(to='games.game'),
        ),
    ]
