# Generated by Django 4.2.1 on 2023-05-13 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_company_game_delete_developer_company_games'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
