# Generated by Django 4.2.1 on 2023-05-13 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_game_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='date_birth',
            new_name='date_founded',
        ),
        migrations.RemoveField(
            model_name='company',
            name='date_death',
        ),
    ]
