# Generated by Django 4.2.1 on 2023-05-13 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_rename_date_birth_company_date_founded_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=60)),
                ('info', models.TextField(blank=True)),
            ],
        ),
        migrations.RenameField(
            model_name='company',
            old_name='bio',
            new_name='info',
        ),
        migrations.RemoveField(
            model_name='game',
            name='game_category',
        ),
        migrations.AddField(
            model_name='game',
            name='game_category',
            field=models.ManyToManyField(to='games.category'),
        ),
    ]
