# Generated by Django 4.2.1 on 2023-05-15 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_alter_company_picture_alter_game_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='ceo',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
