# Generated by Django 4.2.1 on 2023-05-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_company_ceo'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='descript',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
