# Generated by Django 4.2.1 on 2023-05-25 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_company_descript'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='descript',
        ),
    ]
